apiVersion: apps/v1
kind: Deployment
metadata:
  name: "driver-did-btcr"
  namespace: "uni-resolver"
  labels:
    app: "driver-did-btcr"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "driver-did-btcr"
  template:
    metadata:
      labels:
        app: "driver-did-btcr"
    spec:
      containers:
      - name: "driver-did-btcr"
        image: universalresolver/driver-did-btcr:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: "driver-did-btcr"
spec:
  type: NodePort
  selector:
    app: "driver-did-btcr"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080